language: python
dist: bionic

env:
  - TEST="flake8"
  - OS=ubuntu20.04 PY=3 TEST="all"
  - OS=debian10 PY=3 TEST="all"
  - OS=debian10 PY=2 TEST="all"
  - OS=debian9 PY=3 TEST="all"
  - OS=debian9 PY=2 TEST="all"
  - OS=ubuntu18.04 PY=3 TEST="all"
  - OS=ubuntu18.04 PY=2 TEST="all"

services:
  - docker
  - xvfb

before_install:
  - if [ $TEST == "flake8" ]; then sudo apt-get update -qq ; fi
  - if [ $TEST == "flake8" ]; then sudo pip install flake8; fi
  - if [ $TEST != "flake8" ]; then chmod +x .travis/run.sh; fi
  - if [ $TEST != "flake8" ]; then chmod +x .travis/install.sh; fi

before_script:
  - if [ $TEST != "flake8" ]; then docker build -t ndts .travis/${OS}_py${PY}; fi
  - if [ $TEST != "flake8" ]; then docker run  --name  ndts -d -it -v `pwd`:/home/tango -v /tmp/.X11-unix:/tmp/.X11-unix:ro  -e DISPLAY=$DISPLAY   ndts; fi
  - if [ $TEST != "flake8" ]; then .travis/install.sh ${OS} ${PY}; fi

script:
  - if [ $TEST != "flake8" ]; then .travis/run.sh ${TEST} ${PY} ${OS}; fi
  - if [ $TEST == "flake8" ]; then flake8; fi


after-script:
  - if [ $TEST != "flake8" ]; then docker stop ndts; fi
  - if [ $TEST != "flake8" ]; then docker rm ndts; fi
