name: Test Package

on: [push, pull_request]

jobs:

  flake8_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  python3_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian10, debian9, ubuntu18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Update bash files
        run: |
          chmod +x .ci/run.sh
          chmod +x .ci/install.sh
      - name: Build the docker
        env:
          OSYS: ${{ matrix.os }}
        run: docker build -t ndts .ci/${OSYS}_py3
      - name: Run the docker
        run: docker run  --name  ndts -d -it -v `pwd`:/home/tango    ndts
      - name: install tango
        env:
          OSYS: ${{ matrix.os }}
        run: .ci/install.sh ${OSYS} 3
      - name: run tests
        env:
          OSYS: ${{ matrix.os }}
        run: .ci/run.sh all_splitted 3 ${OSYS}
      - name: Stop the docker
        run: docker container stop ndts

  python2_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian10, debian9, ubuntu18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: npm install
      - run: sudo apt-get install xvfb
      - run: Xvfb :99 &
      - name: Update bash files
        run: |
          chmod +x .ci/run.sh
          chmod +x .ci/install.sh
      - name: Build the docker
        env:
          OSYS: ${{ matrix.os }}
        run: docker build -t ndts .ci/${OSYS}_py2
      - name: Run the docker
        run: docker run  --name  ndts -d -it -v `pwd`:/home/tango  -v /tmp/.X11-unix:/tmp/.X11-unix:ro  -e DISPLAY=$DISPLAY   ndts
      - name: install tango
        env:
          OSYS: ${{ matrix.os }}
        run: .ci/install.sh ${OSYS} 2
      - name: run tests
        env:
          OSYS: ${{ matrix.os }}
        run: .ci/run.sh all 2 ${OSYS}
      - name: Stop the docker
        run: docker container stop ndts
